### ISSUE TITLE
Can this script be used to upgrade?

### ISSUE THREAD

**Issue by CyberCam1969** [PietsHost/Nextcloud-Installation-Script#10]
Not really an issue but I want to up grade my NextCloud server from 11.03 to 12.03. I did use the script to create the server. I have my database info and passwords from the text file. Do I need to do anything special besides backing up everything?

**Comment by PietsHost** [comment]
Unfortunately this Script isn't designed for updating an existing Nextcloud installation.

If you want to update from 11.03 to 12.03 there are 2 (or more) ways:
1) Use the web-updater built in to nextcloud
2) use my Nextcloud-Update-Script located here: https://github.com/PietsHost/nextcloud-Update-Script

If you choose my Update-Script, you can start the script with "--backup" flag to create a full backup of your Nextcloud installation. If you start it withouth the "--backup" flag, your files won't get touched - so no loss of data as well ;)
