### ISSUE TITLE
"readOne: command not found"

### ISSUE THREAD

**Issue by emresaracoglu** [PietsHost/Nextcloud-Installation-Script#12]
Hello,

I getting this error:

```
Enter [1-6], [s] or [q]: ./nc_install.sh: line 581: readOne: command not found
^C./nc_install.sh: line 563: printhead: command not found
```

CentOS 7

**Comment by PietsHost** [comment]
both, "readOne" and "printhead" are functions/variables.. Could you please check if your script looks like it should? 
For example: if you copy & paste the content there could be issues with line breaks

**Comment by emresaracoglu** [comment]
Sorry, I notice my mistake. Now working, thank you! :)
