### ISSUE TITLE
403 error after installation

### ISSUE THREAD

**Issue by javielico** [PietsHost/Nextcloud-Installation-Script#13]
After creating the virtual host and pointing to the default host I get an 403 error, the folder uses www-data:www-data and the next cloud install is created on my home folder /home/user/nextcloud, any ideas? I'm using let's encrypt for ssl with certbot.

**Comment by PietsHost** [comment]
Which OS?
httpd-config?
etc.. Please specify more informations about your Server/Software, Installation method, etc.

**Comment by javielico** [comment]
I'm using Ubuntu 16.04 here's my virtual host:
**HTTP:**
```
<VirtualHost *:80>
    ServerAdmin admin@mydomain.com
    ServerName mydomain.com
    DocumentRoot /home/user/nextcloud
    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined
RewriteEngine on
RewriteCond %{SERVER_NAME} =mydomain.com
RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]
</VirtualHost>
```

**HTTPS:**
```
<IfModule mod_ssl.c>
<VirtualHost *:443>
    ServerAdmin admin@mydomain.com
    ServerName mydomain.com
    DocumentRoot /home/user/nextcloud
    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined
SSLCertificateFile /etc/letsencrypt/live/mydomain.com/fullchain.pem
SSLCertificateKeyFile /etc/letsencrypt/live/mydomain.com/privkey.pem
Include /etc/letsencrypt/options-ssl-apache.conf
</VirtualHost>
</IfModule>

```
I've used this guide (https://www.digitalocean.com/community/tutorials/how-to-install-linux-apache-mysql-php-lamp-stack-on-ubuntu-16-04) to install LAMP.

Thanks,
Javi.

**Comment by javielico** [comment]
Got it, just added:
```
<Directory /home/user/nextcloud>
 Options +FollowSymlinks
 AllowOverride All

 <IfModule mod_dav.c>
 Dav off
 </IfModule>

 SetEnv HOME /home/user/nextcloud
 SetEnv HTTP_HOME /home/user/nextcloud
 Satisfy Any

</Directory>
```

**Comment by javielico** [comment]
Still getting this error, after loading the page:
`Error while trying to create admin user: Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'UserUser'@'localhost' (using password: YES)`

And then
`Your data directory and files are probably accessible from the internet because the .htaccess file does not work.`

I've tried to connect to the SQL server using the credentials and it seems to work, any ideas?

**Comment by PietsHost** [comment]
Your server is misconfigured. That has nothing to do with this Installation Script.. Please refer to the official Software documentations.

Thanks!
