### ISSUE TITLE
issue at downloading the latest version

### ISSUE THREAD

**Issue by MojotheShaman** [PietsHost/Nextcloud-Installation-Script#5]
./nc_install.sh: line 1522: curl: command not found
Checking latest version on the Nextcloud download server and if it's possible to download...

Nextcloud version  doesn't exist.

Please check available versions here: https://download.nextcloud.com/server/releases

**Comment by PietsHost** [comment]
Please check the permissions of your target directory/folder. If it‘s not „apache“ (or similiar) you’re getting this error
