### ISSUE TITLE
Script fails if MySQL or Apache is not pre-installed 

### ISSUE THREAD

**Issue by enoch85** [PietsHost/Nextcloud-Installation-Script#7]
In the initial setup give the option to change www root, but it can't be changed if Apache is not installed.

Same goes for MySQL password, if it's not installed it ends up in a loop where you can't proceed.

Maybe add some info that those two should be pre-installed, or install them and set a random password during dependencies installation?

**Comment by PietsHost** [comment]
Thanks for that advice, I'll look into that!

I guess a short query whether Apache/MySQL is installed or not should fix this.

**Comment by enoch85** [comment]
Yeah, or add it and generate some random password. https://github.com/nextcloud/vm/blob/master/nextcloud_install_production.sh#L143-L164

**Comment by PietsHost** [comment]
Hm.. see, this script is not designed to install additional Software like Apache or MySQL.. a random password e.g. is generated for the Nextcloud Admin-User. But it does require the root MySQL-Password to generate both MySQL User + Database

**Comment by PietsHost** [comment]
Fixed with commit https://github.com/PietsHost/Nextcloud-Installation-Script/commit/843744bdd00ad3cd20e9e74796e45a13e74950b4
