### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by tmcpnet** [PietsHost/Nextcloud-Installation-Script#8]
When i execute the script i receive below:

./nc_install.sh: line 7: syntax error near unexpected token `newline'
./nc_install.sh: line 7: `<!DOCTYPE html>'

I have all the prerequisites.

**Comment by PietsHost** [comment]
Could you give me more informations please?

Which OS do you use? How did you get the script? (Copied the script or did you use git clone?) etc.

There's nothing else than a comment in line 7, so there can’t be an error..

Thanks

**Comment by tmcpnet** [comment]
I am running Ubuntu 16.04. I was downloading it manually and was getting the above error.

I pulled it from git and i don't get the error anymore however i get new error:

Below is when the script initiates:

                    Setup			Page 1/3
------+------------+-----------------+------------------------------------
  Nr. |   Status   |     description |    value
------+------------+-----------------+------------------------------------
  1   |     OK     |         Domain: | http://example.com
  2   |     OK     |           name: | my_nextcloud
  3   |     OK     |      directory: | /var/www/html
  4   |     OK     |         folder: | nextcloud1

  5   |     OK     |        DB-Type: | mysql
  6   |     OK     |        DB-Host: | localhost
------+------------+-----------------+------------------------------------
Type [1-6] to change value or [s] to save and go to next page
[q] Quit
Enter [1-6], [s] or [q]: 
-----------------------------

No Nextcloud installation found! Installing continues...

I do have apache installed:

Reading package lists... Done
Building dependency tree       
Reading state information... Done
apache2 is already the newest version (2.4.18-2ubuntu3.4).
0 upgraded, 0 newly installed, 0 to remove and 10 not upgraded.

**Comment by PietsHost** [comment]
Hm, unfortunately I can't see any error message...

But I guess the script just exits after that, is that correct?

**Comment by tmcpnet** [comment]
@PietsHost

That's correct it terminates even tho I have Apache installed.

**Comment by PietsHost** [comment]
Okay, I'll look into that.

For now, you can comment out the lines from 1324 to 1331:
```
if [ $? -eq 0 ]; then
	echo ""
else
	printf $redbg"Apache is not installed/not running. Aborting..."$reset
	echo ""
	sleeping2
	abort
fi
```

That should fix the problem

**Comment by PietsHost** [comment]
@tmcpnet 
I've just setup a Ubuntu 16.04 Server with LAMP and I'm not getting any errors.

Did you check if your Apache is active (running) ?
Can you give me the output of `ps -A | grep 'apache\|httpd'` ?

**Comment by tmcpnet** [comment]
@PietsHost 

With your query i don't get any result.

So i tried below:
1. dpkg --get-selections | grep apache
Result:
apache2						install
apache2-bin					install
apache2-data					install
apache2-utils					install
libapache2-mod-php7.1			install

2. sudo lsof -nPi | grep ":80 (LISTEN)"
Result:
nginx       994     root    8u  IPv4  22655      0t0  TCP *:80 (LISTEN)
nginx       994     root    9u  IPv6  22656      0t0  TCP *:80 (LISTEN)
nginx       995 www-data    8u  IPv4  22655      0t0  TCP *:80 (LISTEN)
nginx       995 www-data    9u  IPv6  22656      0t0  TCP *:80 (LISTEN)
nginx       996 www-data    8u  IPv4  22655      0t0  TCP *:80 (LISTEN)
nginx       996 www-data    9u  IPv6  22656      0t0  TCP *:80 (LISTEN)
nginx       997 www-data    8u  IPv4  22655      0t0  TCP *:80 (LISTEN)
nginx       997 www-data    9u  IPv6  22656      0t0  TCP *:80 (LISTEN)
nginx       998 www-data    8u  IPv4  22655      0t0  TCP *:80 (LISTEN)
nginx       998 www-data    9u  IPv6  22656      0t0  TCP *:80 (LISTEN)

3. When i try to install apache again i see below.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
apache2 is already the newest version (2.4.18-2ubuntu3.4).
0 upgraded, 0 newly installed, 0 to remove and 11 not upgraded.

Is it something wrong on my side?

**Comment by PietsHost** [comment]
You have nginx running on Port 80, but not Apache. That's the reason why the Script cannot find Apache.. So I guess apache2 is installed on your system, but it's not running.

sudo lsof -nPi | grep ":80 (LISTEN)"
```
apache2  13830  www-data    4u  IPv6  39238      0t0  TCP *:80 (LISTEN)
apache2  13831  www-data    4u  IPv6  39238      0t0  TCP *:80 (LISTEN)
apache2  13832  www-data    4u  IPv6  39238      0t0  TCP *:80 (LISTEN)
apache2  13833  www-data    4u  IPv6  39238      0t0  TCP *:80 (LISTEN)
apache2  13834  www-data    4u  IPv6  39238      0t0  TCP *:80 (LISTEN)
```
What do you geht with `service apache2 status` ? 
Output should be similiar to:

```
● apache2.service - LSB: Apache2 web server
   Loaded: loaded (/etc/init.d/apache2; bad; vendor preset: enabled)
  Drop-In: /lib/systemd/system/apache2.service.d
           └─apache2-systemd.conf
   Active: active (running) since So 2017-09-10 19:41:42 CEST; 4h 1min ago

```

**Comment by tmcpnet** [comment]
I get this. It seems apache is not running. Can you tweak your script to support nginx?

apache2.service - LSB: Apache2 web server
   Loaded: loaded (/etc/init.d/apache2; bad; vendor preset: enabled)
  Drop-In: /lib/systemd/system/apache2.service.d
           └─apache2-systemd.conf
   Active: inactive (dead)
     Docs: man:systemd-sysv-generator(8)

Sep 10 13:57:47  apache2.service: apache2.service: Unit cannot be reloaded because it is inactive.

**Comment by PietsHost** [comment]
Sure.

Added nginx support: https://github.com/PietsHost/Nextcloud-Installation-Script/commit/b84cb9f4e6ab31cfe45d3215682dbe249c7e0e11
